### ISSUE TITLE
Ich möche dich bitten die Waffen und Rüstungen in einer Liste zusammenzfassen

### ISSUE THREAD

**Issue by maganrevan** [maganrevan/heroes-of-gods.forumieren.com#1]
Siehe Titel ^^

**Comment by maganrevan** [comment]
Und wie kommst du voran? ;)

**Comment by maganrevan** [comment]
Moin meine Liebe, ich würde gerne hier ein bisschen was mitmachen, deshalb möchte ich dich bitten, dass du dann hier Änderungen etc. postest, bzw. einen kurzen Status gibst, hier können wir dann schauen, und niemand sonst ;) 

Frage, wie lange meinst du noch, brauchst du noch?

**Comment by BiancaMuehlfeldner1** [comment]
http://workupload.com/file/arCcP1zb

Das ist eine Tabelle mit den Waffen die ich für die verschiedenen Klassen angedacht habe.
Kann noch erweitert werden. Die Rüstungen werden nicht so vielfältig denke ich. Zusätzlich fehlen einfach die Werte. (Level, Schaden, etwaige Effekte)

**Comment by BiancaMuehlfeldner1** [comment]
http://workupload.com/file/ysuthBwf

Update: Der Stab für den Krieger flog raus, und der Bogenschütze hat jetzt auch Zugriff auf diese.

**Comment by maganrevan** [comment]
Wie sieht es hier aus? Hast du denn jetzt schon eine komplette Tabelle mit Stats und allem drum und dran ?
